[package]
name = "ios"
edition = "2021"
publish = false

[lib]
name = "ios"
crate-type = ["staticlib"]

[dependencies]
bevy = { version = "0.15" }
game = { path = "../../crates/game" }

[target.aarch64-apple-ios-sim.dependencies]
game = { path = "../../crates/game" }
